# Vectors

$$\boldsymbol{a} = (1,2,3)$$
$$\boldsymbol{b} = (4,0,-5)$$
$$\boldsymbol{c} = (-1,-2,7)$$
$$k = -2$$

Compleate the following vector operations in these 3 methods:
- Manual: using $\LaTeX$
- Python: using lists and `for` loops
- Numpy: using ndarrays and Numpy

The operations are as follows:
- _Vector addition_: $a + b$
- _Dot product_: $ a \cdot b$
- _Scalar multiplication_: $k \, c$
- _Vector subtraction:_ $a - c$
- _Example of a combined vector operation:_ $a -k \, b$
  

## Manual: LaTeX

### Vector addition

$$a + b = (1+4,2+0,3+(-5)) = (5, 2, -2)$$
$$a+b=(5,2, -2)$$

### Dot product

$$a \cdot b=(1\cdot4+2\cdot0+3\cdot(-5))=(4+ 0 -15)=-11$$
$$a \cdot b=-11$$


### Scalar multiplication

$$k \, c=(-1\cdot-2,-2\cdot-2, 7\cdot-2)= (2,4, -14)$$
$$k \, c=(2,4, -14)$$

### Vector subtraction

$$a - c= (1- (-1), 2 - (-2), 3 - 7)= (2,4,-4)$$
$$a - c=(2,4,-4)$$

### Combined vector operation

$$a-k\,b = (1,2,3) -(-2)\,(4,0,-5)=$$
$$(1,2,3)+2 \,(4,0,-5) =$$

$$(1,2,3) + (8, 0,-10) =$$
$$(9,2,-7)$$
$$a-k\,b=(9,2,-7)$$

## Python lists

### Vector addition

In [3]:
a = [1, 2, 3]
b = [4, 0, -5]
c = [-1, -2, 7]
k = -2

result = []
for i in range(3):
    result.append(a[i] + b[i])
print(result)

[5, 2, -2]


In [ ]:
result = []
for x, y in zip(a, b):
    result.append(x+y)
print(result)

[5, 2, -2]


In [ ]:
[x+y for x, y in zip(a, b)]

[5, 2, -2]

### Dot product

In [16]:
result = 0
for i in range(3):
    result+= (a[i] * b[i])
print(result)

-11


In [17]:
sum(x*y for x, y in zip(a, b))

-11

### Scalar multiplication

In [23]:
result = []
for i in range(3):
    result.append(c[i] * k)
print(result)

[2, 4, -14]


In [24]:
[i * k for i in c]

[2, 4, -14]

### Vector subtraction

In [26]:
result = []
for i in range(3):
    result.append(a[i] - c[i])
print(result)

[2, 4, -4]


In [ ]:
[x-y for x, y in zip(a, c)]

[2, 4, -4]

### Combined vector operation

In [ ]:
[x-k*y for x, y in zip(a, b)]

[9, 2, -7]

## Numpy

### Vector addition

In [4]:
import numpy as np
a = np.array(a)
b = np.array(b)
c = np.array(c)

print(a+b)

[ 5  2 -2]


### Dot product

In [5]:
print(np.dot(a, b))

-11


In [7]:
print(a@b)

-11


### Scalar multiplication

In [39]:
print(k * c)

[  2   4 -14]


### Vector subtraction

In [40]:
print(a-c)

[ 2  4 -4]


### Combined vector operation

In [41]:
print(a-k*b)

[ 9  2 -7]
