# Matrices
Let $A$, $B$, $C$ be the matrices:

$$A = \begin{pmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{pmatrix}, \quad
B = \begin{pmatrix} 3 & -1 & -2 \\ -2 & 0 & 1 \\ 5 & -3 & 0 \end{pmatrix}, \quad
C = \begin{pmatrix} -1 & -6 & -2 \\ 3 & 1 & 11 \end{pmatrix}$$

Let the scalar $k = -3$.

Solve the following operations using Numpy.
1. Transpose of $C$. The transpose is usually represented as $C^T$, or as $C^t$, or as $C'$.
2. Matrix addition: $A + B$
3. Matrix subtraction: $A - B$
4. Scalar-matrix product: $k B$
5. Matrix product: $AB$
6. Use a Numpy function to calculate the number of rows and columns of matrix $C$.
7. Is the product $BC$ possible? If so, calculate it.
8. Is the product $CB$ possible? If so, calculate it.
9. Calculate the trace of matrix $A$.

In [11]:
import numpy as np

A = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
B = np.matrix([[3,-1,-2],[-2,0,1],[5,-3,0]])
C = np.matrix([[-1,-6,-2],[3,1,11]])
k = -3

## Transposition of matrices

In [2]:
print(np.transpose(C))

[[-1  3]
 [-6  1]
 [-2 11]]


## Matrix addition

In [3]:
print(A+B)

[[ 4  1  1]
 [ 2  5  7]
 [12  5  9]]


## Matrix substraction

In [4]:
print(A-B)

[[-2  3  5]
 [ 6  5  5]
 [ 2 11  9]]


## Scalar-matrix product

In [5]:
print(k*B)

[[ -9   3   6]
 [  6   0  -3]
 [-15   9   0]]


## Matrix product

In [6]:
print(A*B)

[[ 14 -10   0]
 [ 32 -22  -3]
 [ 50 -34  -6]]


In [18]:
print(A@B)

[[ 14 -10   0]
 [ 32 -22  -3]
 [ 50 -34  -6]]


In [21]:
print(A.dot(B))

[[ 14 -10   0]
 [ 32 -22  -3]
 [ 50 -34  -6]]


## Matrix dimension

In [13]:
np.shape(C)

(2, 3)

## Posible product

In [16]:
try:
    B*C
except:
    print("ERROR: Shapes don't align")

ERROR: Shapes don't align


In [15]:
print(C*B)

[[ -1   7  -4]
 [ 62 -36  -5]]


## Matrix trace

$$A = \begin{pmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{pmatrix}$$
Trace $A$: $1 + 5 + 9 = 15$

In [17]:
print(np.trace(A))

15
